apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaler-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-scaler
  namespace: default
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-scaler-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: scaler-account
  namespace: default
roleRef:
  kind: Role
  name: deployment-scaler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-scaler
  namespace: default
spec:
  schedule: "*/60 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: scaler-account
          containers:
          - name: scaler
            image: bitnami/kubectl
            command:
            - bash
            - -c
            - |
              set -x;
              n=$((RANDOM % 9 + 2));
              echo "Scaling Busybox to $n replicas";
              kubectl scale deployment/busybox --replicas=$n || echo "Failed to scale with status $?"
          restartPolicy: OnFailure
